### ISSUE TITLE
ItemModule: compareCustomItem メソッドに、displayName = null なアイテムを渡すとぬるぽ

### ISSUE THREAD

**Issue by 104toki** [XelticaMC/X-Core#219]
「カスタムアイテムでない、かつ名前を変更していない」アイテムのうち「人参付きの釣り竿」と「歪んだきのこ付きの棒」が引数に入ると、`java.lang.NullPointerException: null`が出る。

実行コード（SetMarkerMdule.kt:414）
`if (ItemModule.compareCustomItem(item, createMarkerToolAD())) return true`

スタックトレース抜粋
```Could not pass event PlayerInteractEvent to XCore v3.1.2
java.lang.NullPointerException: null
        at work.xeltica.craft.core.modules.item.ItemModule.compareCustomItem(ItemModule.kt:79) ~[XCore.jar:?]
        at work.xeltica.craft.core.modules.setMarker.SetMarkerModule.isMarkerTool(SetMarkerModule.kt:414) ~[XCore.jar:?]
        at work.xeltica.craft.core.modules.setMarker.SetMarkerHandler.onRClick(SetMarkerHandler.kt:27) ~[XCore.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor143.execute(Unknown Source) ~[?:?]
        ...

**Comment by EbiseLutica** [comment]
https://github.com/XelticaMC/X-Core/blob/d185c60e027252e59815216c8083640ff8a0829f/src/main/java/work/xeltica/craft/core/modules/item/ItemModule.kt#L79-L80

ここでnullチェックをせず握りつぶしていたのが原因

カスタムアイテムはdisplayNameを必ず持つ想定なので、ここでnullだった場合はfalseを返すようにする
